# SPDX-License-Identifier: MIT

require conf/distro/cassini.conf

DISTRO = "auto-ad-nexios"
DISTRO_NAME = "Auto AD Nexios"

# Auto AD Nexios requires the PREEMPT_RT kernel profile.
PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-rt"

# Auto AD Nexios is based on Cassini and keeps EWAOL image-feature
# compatibility for the Arm Auto Solutions baremetal image flow.
BASE_DISTRO = "cassini"
DISTROOVERRIDES .= ":ewaol:${BASE_DISTRO}"

CASSINI_ADMIN_ACCOUNT = "ewaol"
DISTRO_FEATURES:append = " ewaol-cloud"
DISTRO_FEATURES:append:auto-ad-nexios = " security integrity overlayfs"

APOLLO_DM_VERITY ?= "1"

IMAGE_CLASSES:append:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', ' dm-verity-img', '', d)}"
DM_VERITY_IMAGE:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', 'nexios-image', '', d)}"
DM_VERITY_IMAGE_TYPE:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', 'ext4', '', d)}"
DM_VERITY_SEPARATE_HASH:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', '0', '', d)}"
INITRAMFS_IMAGE:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', 'nexios-initramfs-image', '', d)}"
INITRAMFS_FSTYPES:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', 'cpio.gz', '', d)}"
INITRD_ARCHIVE:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', '${INITRAMFS_IMAGE}-${MACHINE}.${INITRAMFS_FSTYPES}', '', d)}"

OVERLAYFS_ETC_MOUNT_POINT:auto-ad-nexios = "/rootrw"
OVERLAYFS_ETC_FSTYPE:auto-ad-nexios = "ext4"
OVERLAYFS_ETC_DEVICE:auto-ad-nexios = "LABEL=rootrw"
OVERLAYFS_ETC_MOUNT_OPTIONS:auto-ad-nexios = "defaults"
OVERLAYFS_ETC_CREATE_MOUNT_DIRS:auto-ad-nexios = "0"

USER_CLASSES:append = " ewaol-features"
VIRTUAL-RUNTIME_ota_update = "no-ota"

WKS_FILE:apollo-fvp:auto-ad-nexios = "${@bb.utils.contains('APOLLO_DM_VERITY', '1', 'apollo-fvp-auto-ad-nexios-ab.wks.in', 'apollo-fvp-auto-ad-nexios-ab-plain.wks.in', d)}"
WKS_FILE_DEPENDS:append:apollo-fvp:auto-ad-nexios = " auto-ad-nexios-boot-state"

TEST_SUITES:apollo-fvp:auto-ad-nexios = "\
    ping \
    ssh \
    test_00_rse \
    test_00_secure_partition \
    test_01_auto_ad_nexios_uki_boot \
    test_02_safety_boot \
    test_10_linuxboot \
    test_20_aspen_ap_dsu \
    test_30_configurable_pc_cores \
    fvp_boot \
    fvp_devices \
    "

TEST_TARGET:apollo-fvp:auto-ad-nexios = "HSOCOEFVPTarget"
TEST_FVP_DEVICES:apollo-fvp:auto-ad-nexios = "rtc watchdog networking virtiorng"
TESTIMAGE_UPDATE_VARS:append:apollo-fvp:auto-ad-nexios = " TEST_FVP_DEVICES"

HSOC_RUN_TEST_SKIP_SUITES:apollo-fvp:auto-ad-nexios = "\
    test_00_aspen_boot \
    test_10_pfdi \
    test_10_ras_cpu \
    test_10_sbistc_integration \
    test_20_hipc_baremetal \
    test_50_cryptographic_extension \
    test_99_uefi_secure_boot \
    test_100_fwu \
    "
HSOC_RUN_TEST_SKIP_EXTRA_LANES:apollo-fvp:auto-ad-nexios = "\
    extra-sw-ref-stack-unittests \
    "
HSOC_RUN_TEST_SKIP_REASON:apollo-fvp:auto-ad-nexios = "excluded_by_hsoc_yocto_build_config"
